//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_pasajero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_pasajero()
        {
            this.Tb_pago = new HashSet<Tb_pago>();
            this.Tb_reserva = new HashSet<Tb_reserva>();
        }
    
        public int idPasajero { get; set; }
        public string nombre { get; set; }
        public string apaterno { get; set; }
        public string amaterno { get; set; }
        public string tipo_documento { get; set; }
        public string num_documento { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string genero { get; set; }
        public Nullable<System.DateTime> F_Nacimiento { get; set; }
        public Nullable<System.DateTime> F_Registro { get; set; }
        public Nullable<System.DateTime> F_Modificacion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> idPais { get; set; }
        public Nullable<int> id_Rol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_pago> Tb_pago { get; set; }
        public virtual Tb_pais Tb_pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_reserva> Tb_reserva { get; set; }
        public virtual Tb_rol Tb_rol { get; set; }
    }
}
