//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_MVC.ProxyPasajeros {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasajeroBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Reservas")]
    [System.SerializableAttribute()]
    public partial class PasajeroBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AerolineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDepartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedioPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomDepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoVueloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aerolinea {
            get {
                return this.AerolineaField;
            }
            set {
                if ((object.ReferenceEquals(this.AerolineaField, value) != true)) {
                    this.AerolineaField = value;
                    this.RaisePropertyChanged("Aerolinea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNac {
            get {
                return this.FechaNacField;
            }
            set {
                if ((this.FechaNacField.Equals(value) != true)) {
                    this.FechaNacField = value;
                    this.RaisePropertyChanged("FechaNac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPago {
            get {
                return this.FechaPagoField;
            }
            set {
                if ((this.FechaPagoField.Equals(value) != true)) {
                    this.FechaPagoField = value;
                    this.RaisePropertyChanged("FechaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneroField, value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDepart {
            get {
                return this.IdDepartField;
            }
            set {
                if ((this.IdDepartField.Equals(value) != true)) {
                    this.IdDepartField = value;
                    this.RaisePropertyChanged("IdDepart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPais {
            get {
                return this.IdPaisField;
            }
            set {
                if ((this.IdPaisField.Equals(value) != true)) {
                    this.IdPaisField = value;
                    this.RaisePropertyChanged("IdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedioPago {
            get {
                return this.MedioPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.MedioPagoField, value) != true)) {
                    this.MedioPagoField = value;
                    this.RaisePropertyChanged("MedioPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomDep {
            get {
                return this.NomDepField;
            }
            set {
                if ((object.ReferenceEquals(this.NomDepField, value) != true)) {
                    this.NomDepField = value;
                    this.RaisePropertyChanged("NomDep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPais {
            get {
                return this.NomPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.NomPaisField, value) != true)) {
                    this.NomPaisField = value;
                    this.RaisePropertyChanged("NomPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroComprobante {
            get {
                return this.NumeroComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroComprobanteField, value) != true)) {
                    this.NumeroComprobanteField = value;
                    this.RaisePropertyChanged("NumeroComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento {
            get {
                return this.NumeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoField, value) != true)) {
                    this.NumeroDocumentoField = value;
                    this.RaisePropertyChanged("NumeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((object.ReferenceEquals(this.PrecioField, value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruc {
            get {
                return this.RucField;
            }
            set {
                if ((object.ReferenceEquals(this.RucField, value) != true)) {
                    this.RucField = value;
                    this.RaisePropertyChanged("Ruc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoComprobante {
            get {
                return this.TipoComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoComprobanteField, value) != true)) {
                    this.TipoComprobanteField = value;
                    this.RaisePropertyChanged("TipoComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoVuelo {
            get {
                return this.TipoVueloField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoVueloField, value) != true)) {
                    this.TipoVueloField = value;
                    this.RaisePropertyChanged("TipoVuelo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyPasajeros.IServicioPasajero")]
    public interface IServicioPasajero {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/GetPasajeroDetallePagoPorDni", ReplyAction="http://tempuri.org/IServicioPasajero/GetPasajeroDetallePagoPorDniResponse")]
        Proyecto_MVC.ProxyPasajeros.PasajeroBE[] GetPasajeroDetallePagoPorDni(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/GetPasajeroDetallePagoPorDni", ReplyAction="http://tempuri.org/IServicioPasajero/GetPasajeroDetallePagoPorDniResponse")]
        System.Threading.Tasks.Task<Proyecto_MVC.ProxyPasajeros.PasajeroBE[]> GetPasajeroDetallePagoPorDniAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/ListarPasajerosPorDepartamento", ReplyAction="http://tempuri.org/IServicioPasajero/ListarPasajerosPorDepartamentoResponse")]
        Proyecto_MVC.ProxyPasajeros.PasajeroBE[] ListarPasajerosPorDepartamento(string departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/ListarPasajerosPorDepartamento", ReplyAction="http://tempuri.org/IServicioPasajero/ListarPasajerosPorDepartamentoResponse")]
        System.Threading.Tasks.Task<Proyecto_MVC.ProxyPasajeros.PasajeroBE[]> ListarPasajerosPorDepartamentoAsync(string departamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/ListarPasajerosPorGenero", ReplyAction="http://tempuri.org/IServicioPasajero/ListarPasajerosPorGeneroResponse")]
        Proyecto_MVC.ProxyPasajeros.PasajeroBE[] ListarPasajerosPorGenero(string genero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/ListarPasajerosPorGenero", ReplyAction="http://tempuri.org/IServicioPasajero/ListarPasajerosPorGeneroResponse")]
        System.Threading.Tasks.Task<Proyecto_MVC.ProxyPasajeros.PasajeroBE[]> ListarPasajerosPorGeneroAsync(string genero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/ListarPasajerosPorPais", ReplyAction="http://tempuri.org/IServicioPasajero/ListarPasajerosPorPaisResponse")]
        Proyecto_MVC.ProxyPasajeros.PasajeroBE[] ListarPasajerosPorPais(string pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/ListarPasajerosPorPais", ReplyAction="http://tempuri.org/IServicioPasajero/ListarPasajerosPorPaisResponse")]
        System.Threading.Tasks.Task<Proyecto_MVC.ProxyPasajeros.PasajeroBE[]> ListarPasajerosPorPaisAsync(string pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/ListarPasajeros", ReplyAction="http://tempuri.org/IServicioPasajero/ListarPasajerosResponse")]
        Proyecto_MVC.ProxyPasajeros.PasajeroBE[] ListarPasajeros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/ListarPasajeros", ReplyAction="http://tempuri.org/IServicioPasajero/ListarPasajerosResponse")]
        System.Threading.Tasks.Task<Proyecto_MVC.ProxyPasajeros.PasajeroBE[]> ListarPasajerosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/ListarPaises", ReplyAction="http://tempuri.org/IServicioPasajero/ListarPaisesResponse")]
        Proyecto_MVC.ProxyPasajeros.PasajeroBE[] ListarPaises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/ListarPaises", ReplyAction="http://tempuri.org/IServicioPasajero/ListarPaisesResponse")]
        System.Threading.Tasks.Task<Proyecto_MVC.ProxyPasajeros.PasajeroBE[]> ListarPaisesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/ListarDepartamentos", ReplyAction="http://tempuri.org/IServicioPasajero/ListarDepartamentosResponse")]
        Proyecto_MVC.ProxyPasajeros.PasajeroBE[] ListarDepartamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/ListarDepartamentos", ReplyAction="http://tempuri.org/IServicioPasajero/ListarDepartamentosResponse")]
        System.Threading.Tasks.Task<Proyecto_MVC.ProxyPasajeros.PasajeroBE[]> ListarDepartamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/GetContarPasajerosPorPais", ReplyAction="http://tempuri.org/IServicioPasajero/GetContarPasajerosPorPaisResponse")]
        short GetContarPasajerosPorPais(string pais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPasajero/GetContarPasajerosPorPais", ReplyAction="http://tempuri.org/IServicioPasajero/GetContarPasajerosPorPaisResponse")]
        System.Threading.Tasks.Task<short> GetContarPasajerosPorPaisAsync(string pais);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPasajeroChannel : Proyecto_MVC.ProxyPasajeros.IServicioPasajero, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPasajeroClient : System.ServiceModel.ClientBase<Proyecto_MVC.ProxyPasajeros.IServicioPasajero>, Proyecto_MVC.ProxyPasajeros.IServicioPasajero {
        
        public ServicioPasajeroClient() {
        }
        
        public ServicioPasajeroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPasajeroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPasajeroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPasajeroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Proyecto_MVC.ProxyPasajeros.PasajeroBE[] GetPasajeroDetallePagoPorDni(string dni) {
            return base.Channel.GetPasajeroDetallePagoPorDni(dni);
        }
        
        public System.Threading.Tasks.Task<Proyecto_MVC.ProxyPasajeros.PasajeroBE[]> GetPasajeroDetallePagoPorDniAsync(string dni) {
            return base.Channel.GetPasajeroDetallePagoPorDniAsync(dni);
        }
        
        public Proyecto_MVC.ProxyPasajeros.PasajeroBE[] ListarPasajerosPorDepartamento(string departamento) {
            return base.Channel.ListarPasajerosPorDepartamento(departamento);
        }
        
        public System.Threading.Tasks.Task<Proyecto_MVC.ProxyPasajeros.PasajeroBE[]> ListarPasajerosPorDepartamentoAsync(string departamento) {
            return base.Channel.ListarPasajerosPorDepartamentoAsync(departamento);
        }
        
        public Proyecto_MVC.ProxyPasajeros.PasajeroBE[] ListarPasajerosPorGenero(string genero) {
            return base.Channel.ListarPasajerosPorGenero(genero);
        }
        
        public System.Threading.Tasks.Task<Proyecto_MVC.ProxyPasajeros.PasajeroBE[]> ListarPasajerosPorGeneroAsync(string genero) {
            return base.Channel.ListarPasajerosPorGeneroAsync(genero);
        }
        
        public Proyecto_MVC.ProxyPasajeros.PasajeroBE[] ListarPasajerosPorPais(string pais) {
            return base.Channel.ListarPasajerosPorPais(pais);
        }
        
        public System.Threading.Tasks.Task<Proyecto_MVC.ProxyPasajeros.PasajeroBE[]> ListarPasajerosPorPaisAsync(string pais) {
            return base.Channel.ListarPasajerosPorPaisAsync(pais);
        }
        
        public Proyecto_MVC.ProxyPasajeros.PasajeroBE[] ListarPasajeros() {
            return base.Channel.ListarPasajeros();
        }
        
        public System.Threading.Tasks.Task<Proyecto_MVC.ProxyPasajeros.PasajeroBE[]> ListarPasajerosAsync() {
            return base.Channel.ListarPasajerosAsync();
        }
        
        public Proyecto_MVC.ProxyPasajeros.PasajeroBE[] ListarPaises() {
            return base.Channel.ListarPaises();
        }
        
        public System.Threading.Tasks.Task<Proyecto_MVC.ProxyPasajeros.PasajeroBE[]> ListarPaisesAsync() {
            return base.Channel.ListarPaisesAsync();
        }
        
        public Proyecto_MVC.ProxyPasajeros.PasajeroBE[] ListarDepartamentos() {
            return base.Channel.ListarDepartamentos();
        }
        
        public System.Threading.Tasks.Task<Proyecto_MVC.ProxyPasajeros.PasajeroBE[]> ListarDepartamentosAsync() {
            return base.Channel.ListarDepartamentosAsync();
        }
        
        public short GetContarPasajerosPorPais(string pais) {
            return base.Channel.GetContarPasajerosPorPais(pais);
        }
        
        public System.Threading.Tasks.Task<short> GetContarPasajerosPorPaisAsync(string pais) {
            return base.Channel.GetContarPasajerosPorPaisAsync(pais);
        }
    }
}
