//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_MVC.ProxyReservas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Reservas")]
    [System.SerializableAttribute()]
    public partial class ReservaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_LlegadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_SalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAerolineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDepartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreAeropuertoDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreAeropuertoOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_AerolineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_PaisDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_PaisOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_ciudadDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_ciudadOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_asientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Asiento {
            get {
                return this.AsientoField;
            }
            set {
                if ((object.ReferenceEquals(this.AsientoField, value) != true)) {
                    this.AsientoField = value;
                    this.RaisePropertyChanged("Asiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Llegada {
            get {
                return this.Fecha_LlegadaField;
            }
            set {
                if ((this.Fecha_LlegadaField.Equals(value) != true)) {
                    this.Fecha_LlegadaField = value;
                    this.RaisePropertyChanged("Fecha_Llegada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Salida {
            get {
                return this.Fecha_SalidaField;
            }
            set {
                if ((this.Fecha_SalidaField.Equals(value) != true)) {
                    this.Fecha_SalidaField = value;
                    this.RaisePropertyChanged("Fecha_Salida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genero {
            get {
                return this.GeneroField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneroField, value) != true)) {
                    this.GeneroField = value;
                    this.RaisePropertyChanged("Genero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAerolinea {
            get {
                return this.IdAerolineaField;
            }
            set {
                if ((this.IdAerolineaField.Equals(value) != true)) {
                    this.IdAerolineaField = value;
                    this.RaisePropertyChanged("IdAerolinea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDepart {
            get {
                return this.IdDepartField;
            }
            set {
                if ((this.IdDepartField.Equals(value) != true)) {
                    this.IdDepartField = value;
                    this.RaisePropertyChanged("IdDepart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPais {
            get {
                return this.IdPaisField;
            }
            set {
                if ((this.IdPaisField.Equals(value) != true)) {
                    this.IdPaisField = value;
                    this.RaisePropertyChanged("IdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAeropuertoDestino {
            get {
                return this.NombreAeropuertoDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreAeropuertoDestinoField, value) != true)) {
                    this.NombreAeropuertoDestinoField = value;
                    this.RaisePropertyChanged("NombreAeropuertoDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAeropuertoOrigen {
            get {
                return this.NombreAeropuertoOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreAeropuertoOrigenField, value) != true)) {
                    this.NombreAeropuertoOrigenField = value;
                    this.RaisePropertyChanged("NombreAeropuertoOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Aerolinea {
            get {
                return this.Nombre_AerolineaField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_AerolineaField, value) != true)) {
                    this.Nombre_AerolineaField = value;
                    this.RaisePropertyChanged("Nombre_Aerolinea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_PaisDestino {
            get {
                return this.Nombre_PaisDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_PaisDestinoField, value) != true)) {
                    this.Nombre_PaisDestinoField = value;
                    this.RaisePropertyChanged("Nombre_PaisDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_PaisOrigen {
            get {
                return this.Nombre_PaisOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_PaisOrigenField, value) != true)) {
                    this.Nombre_PaisOrigenField = value;
                    this.RaisePropertyChanged("Nombre_PaisOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_ciudadDestino {
            get {
                return this.Nombre_ciudadDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_ciudadDestinoField, value) != true)) {
                    this.Nombre_ciudadDestinoField = value;
                    this.RaisePropertyChanged("Nombre_ciudadDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_ciudadOrigen {
            get {
                return this.Nombre_ciudadOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_ciudadOrigenField, value) != true)) {
                    this.Nombre_ciudadOrigenField = value;
                    this.RaisePropertyChanged("Nombre_ciudadOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumDocumento {
            get {
                return this.NumDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumDocumentoField, value) != true)) {
                    this.NumDocumentoField = value;
                    this.RaisePropertyChanged("NumDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_asiento {
            get {
                return this.Tipo_asientoField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_asientoField, value) != true)) {
                    this.Tipo_asientoField = value;
                    this.RaisePropertyChanged("Tipo_asiento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VueloBE", Namespace="http://schemas.datacontract.org/2004/07/WCF_Reservas")]
    [System.SerializableAttribute()]
    public partial class VueloBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_LlegadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_SalidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAerolineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAeropuertoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAsientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAvionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDepartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LetraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreAeropuertoDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreAeropuertoOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_AerolineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_PaisDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_PaisOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_departamentoDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_VueloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Llegada {
            get {
                return this.Fecha_LlegadaField;
            }
            set {
                if ((this.Fecha_LlegadaField.Equals(value) != true)) {
                    this.Fecha_LlegadaField = value;
                    this.RaisePropertyChanged("Fecha_Llegada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_Salida {
            get {
                return this.Fecha_SalidaField;
            }
            set {
                if ((this.Fecha_SalidaField.Equals(value) != true)) {
                    this.Fecha_SalidaField = value;
                    this.RaisePropertyChanged("Fecha_Salida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fila {
            get {
                return this.FilaField;
            }
            set {
                if ((object.ReferenceEquals(this.FilaField, value) != true)) {
                    this.FilaField = value;
                    this.RaisePropertyChanged("Fila");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAerolinea {
            get {
                return this.IdAerolineaField;
            }
            set {
                if ((this.IdAerolineaField.Equals(value) != true)) {
                    this.IdAerolineaField = value;
                    this.RaisePropertyChanged("IdAerolinea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAeropuerto {
            get {
                return this.IdAeropuertoField;
            }
            set {
                if ((this.IdAeropuertoField.Equals(value) != true)) {
                    this.IdAeropuertoField = value;
                    this.RaisePropertyChanged("IdAeropuerto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAsiento {
            get {
                return this.IdAsientoField;
            }
            set {
                if ((this.IdAsientoField.Equals(value) != true)) {
                    this.IdAsientoField = value;
                    this.RaisePropertyChanged("IdAsiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAvion {
            get {
                return this.IdAvionField;
            }
            set {
                if ((this.IdAvionField.Equals(value) != true)) {
                    this.IdAvionField = value;
                    this.RaisePropertyChanged("IdAvion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDepart {
            get {
                return this.IdDepartField;
            }
            set {
                if ((this.IdDepartField.Equals(value) != true)) {
                    this.IdDepartField = value;
                    this.RaisePropertyChanged("IdDepart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDepartamento {
            get {
                return this.IdDepartamentoField;
            }
            set {
                if ((this.IdDepartamentoField.Equals(value) != true)) {
                    this.IdDepartamentoField = value;
                    this.RaisePropertyChanged("IdDepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDestino {
            get {
                return this.IdDestinoField;
            }
            set {
                if ((this.IdDestinoField.Equals(value) != true)) {
                    this.IdDestinoField = value;
                    this.RaisePropertyChanged("IdDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPais {
            get {
                return this.IdPaisField;
            }
            set {
                if ((this.IdPaisField.Equals(value) != true)) {
                    this.IdPaisField = value;
                    this.RaisePropertyChanged("IdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdReserva {
            get {
                return this.IdReservaField;
            }
            set {
                if ((this.IdReservaField.Equals(value) != true)) {
                    this.IdReservaField = value;
                    this.RaisePropertyChanged("IdReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Letra {
            get {
                return this.LetraField;
            }
            set {
                if ((object.ReferenceEquals(this.LetraField, value) != true)) {
                    this.LetraField = value;
                    this.RaisePropertyChanged("Letra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAeropuertoDestino {
            get {
                return this.NombreAeropuertoDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreAeropuertoDestinoField, value) != true)) {
                    this.NombreAeropuertoDestinoField = value;
                    this.RaisePropertyChanged("NombreAeropuertoDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAeropuertoOrigen {
            get {
                return this.NombreAeropuertoOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreAeropuertoOrigenField, value) != true)) {
                    this.NombreAeropuertoOrigenField = value;
                    this.RaisePropertyChanged("NombreAeropuertoOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Aerolinea {
            get {
                return this.Nombre_AerolineaField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_AerolineaField, value) != true)) {
                    this.Nombre_AerolineaField = value;
                    this.RaisePropertyChanged("Nombre_Aerolinea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Departamento {
            get {
                return this.Nombre_DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_DepartamentoField, value) != true)) {
                    this.Nombre_DepartamentoField = value;
                    this.RaisePropertyChanged("Nombre_Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_PaisDestino {
            get {
                return this.Nombre_PaisDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_PaisDestinoField, value) != true)) {
                    this.Nombre_PaisDestinoField = value;
                    this.RaisePropertyChanged("Nombre_PaisDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_PaisOrigen {
            get {
                return this.Nombre_PaisOrigenField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_PaisOrigenField, value) != true)) {
                    this.Nombre_PaisOrigenField = value;
                    this.RaisePropertyChanged("Nombre_PaisOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_departamentoDestino {
            get {
                return this.Nombre_departamentoDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_departamentoDestinoField, value) != true)) {
                    this.Nombre_departamentoDestinoField = value;
                    this.RaisePropertyChanged("Nombre_departamentoDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo_Vuelo {
            get {
                return this.Tipo_VueloField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_VueloField, value) != true)) {
                    this.Tipo_VueloField = value;
                    this.RaisePropertyChanged("Tipo_Vuelo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyReservas.IServicioReserva")]
    public interface IServicioReserva {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservasPorCiudadOrigen", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservasPorCiudadOrigenResponse")]
        Proyecto_MVC.ProxyReservas.ReservaBE[] ListarReservasPorCiudadOrigen(string ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservasPorCiudadOrigen", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservasPorCiudadOrigenResponse")]
        System.Threading.Tasks.Task<Proyecto_MVC.ProxyReservas.ReservaBE[]> ListarReservasPorCiudadOrigenAsync(string ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservasPorCiudadDestino", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservasPorCiudadDestinoResponse")]
        Proyecto_MVC.ProxyReservas.ReservaBE[] ListarReservasPorCiudadDestino(string ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservasPorCiudadDestino", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservasPorCiudadDestinoResponse")]
        System.Threading.Tasks.Task<Proyecto_MVC.ProxyReservas.ReservaBE[]> ListarReservasPorCiudadDestinoAsync(string ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservas", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservasResponse")]
        Proyecto_MVC.ProxyReservas.ReservaBE[] ListarReservas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservas", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservasResponse")]
        System.Threading.Tasks.Task<Proyecto_MVC.ProxyReservas.ReservaBE[]> ListarReservasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservasPorFechaSalida", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservasPorFechaSalidaResponse")]
        Proyecto_MVC.ProxyReservas.ReservaBE[] ListarReservasPorFechaSalida(System.DateTime fecha1, System.DateTime fecha2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservasPorFechaSalida", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservasPorFechaSalidaResponse")]
        System.Threading.Tasks.Task<Proyecto_MVC.ProxyReservas.ReservaBE[]> ListarReservasPorFechaSalidaAsync(System.DateTime fecha1, System.DateTime fecha2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservasPorFechaLlegada", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservasPorFechaLlegadaResponse")]
        Proyecto_MVC.ProxyReservas.ReservaBE[] ListarReservasPorFechaLlegada(System.DateTime fecha1, System.DateTime fecha2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservasPorFechaLlegada", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservasPorFechaLlegadaResponse")]
        System.Threading.Tasks.Task<Proyecto_MVC.ProxyReservas.ReservaBE[]> ListarReservasPorFechaLlegadaAsync(System.DateTime fecha1, System.DateTime fecha2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservasPorDni", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservasPorDniResponse")]
        Proyecto_MVC.ProxyReservas.ReservaBE[] ListarReservasPorDni(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarReservasPorDni", ReplyAction="http://tempuri.org/IServicioReserva/ListarReservasPorDniResponse")]
        System.Threading.Tasks.Task<Proyecto_MVC.ProxyReservas.ReservaBE[]> ListarReservasPorDniAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarDepartamentos", ReplyAction="http://tempuri.org/IServicioReserva/ListarDepartamentosResponse")]
        Proyecto_MVC.ProxyReservas.VueloBE[] ListarDepartamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioReserva/ListarDepartamentos", ReplyAction="http://tempuri.org/IServicioReserva/ListarDepartamentosResponse")]
        System.Threading.Tasks.Task<Proyecto_MVC.ProxyReservas.VueloBE[]> ListarDepartamentosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioReservaChannel : Proyecto_MVC.ProxyReservas.IServicioReserva, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioReservaClient : System.ServiceModel.ClientBase<Proyecto_MVC.ProxyReservas.IServicioReserva>, Proyecto_MVC.ProxyReservas.IServicioReserva {
        
        public ServicioReservaClient() {
        }
        
        public ServicioReservaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioReservaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReservaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReservaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Proyecto_MVC.ProxyReservas.ReservaBE[] ListarReservasPorCiudadOrigen(string ciudad) {
            return base.Channel.ListarReservasPorCiudadOrigen(ciudad);
        }
        
        public System.Threading.Tasks.Task<Proyecto_MVC.ProxyReservas.ReservaBE[]> ListarReservasPorCiudadOrigenAsync(string ciudad) {
            return base.Channel.ListarReservasPorCiudadOrigenAsync(ciudad);
        }
        
        public Proyecto_MVC.ProxyReservas.ReservaBE[] ListarReservasPorCiudadDestino(string ciudad) {
            return base.Channel.ListarReservasPorCiudadDestino(ciudad);
        }
        
        public System.Threading.Tasks.Task<Proyecto_MVC.ProxyReservas.ReservaBE[]> ListarReservasPorCiudadDestinoAsync(string ciudad) {
            return base.Channel.ListarReservasPorCiudadDestinoAsync(ciudad);
        }
        
        public Proyecto_MVC.ProxyReservas.ReservaBE[] ListarReservas() {
            return base.Channel.ListarReservas();
        }
        
        public System.Threading.Tasks.Task<Proyecto_MVC.ProxyReservas.ReservaBE[]> ListarReservasAsync() {
            return base.Channel.ListarReservasAsync();
        }
        
        public Proyecto_MVC.ProxyReservas.ReservaBE[] ListarReservasPorFechaSalida(System.DateTime fecha1, System.DateTime fecha2) {
            return base.Channel.ListarReservasPorFechaSalida(fecha1, fecha2);
        }
        
        public System.Threading.Tasks.Task<Proyecto_MVC.ProxyReservas.ReservaBE[]> ListarReservasPorFechaSalidaAsync(System.DateTime fecha1, System.DateTime fecha2) {
            return base.Channel.ListarReservasPorFechaSalidaAsync(fecha1, fecha2);
        }
        
        public Proyecto_MVC.ProxyReservas.ReservaBE[] ListarReservasPorFechaLlegada(System.DateTime fecha1, System.DateTime fecha2) {
            return base.Channel.ListarReservasPorFechaLlegada(fecha1, fecha2);
        }
        
        public System.Threading.Tasks.Task<Proyecto_MVC.ProxyReservas.ReservaBE[]> ListarReservasPorFechaLlegadaAsync(System.DateTime fecha1, System.DateTime fecha2) {
            return base.Channel.ListarReservasPorFechaLlegadaAsync(fecha1, fecha2);
        }
        
        public Proyecto_MVC.ProxyReservas.ReservaBE[] ListarReservasPorDni(string dni) {
            return base.Channel.ListarReservasPorDni(dni);
        }
        
        public System.Threading.Tasks.Task<Proyecto_MVC.ProxyReservas.ReservaBE[]> ListarReservasPorDniAsync(string dni) {
            return base.Channel.ListarReservasPorDniAsync(dni);
        }
        
        public Proyecto_MVC.ProxyReservas.VueloBE[] ListarDepartamentos() {
            return base.Channel.ListarDepartamentos();
        }
        
        public System.Threading.Tasks.Task<Proyecto_MVC.ProxyReservas.VueloBE[]> ListarDepartamentosAsync() {
            return base.Channel.ListarDepartamentosAsync();
        }
    }
}
