//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Reservas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Agencia_BDEntities1 : DbContext
    {
        public Agencia_BDEntities1()
            : base("name=Agencia_BDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_aerolinea> Tb_aerolinea { get; set; }
        public virtual DbSet<Tb_aeropuerto> Tb_aeropuerto { get; set; }
        public virtual DbSet<Tb_asiento> Tb_asiento { get; set; }
        public virtual DbSet<Tb_avion> Tb_avion { get; set; }
        public virtual DbSet<Tb_departamento> Tb_departamento { get; set; }
        public virtual DbSet<Tb_Destino> Tb_Destino { get; set; }
        public virtual DbSet<Tb_pago> Tb_pago { get; set; }
        public virtual DbSet<Tb_pais> Tb_pais { get; set; }
        public virtual DbSet<Tb_pasajero> Tb_pasajero { get; set; }
        public virtual DbSet<Tb_reserva> Tb_reserva { get; set; }
        public virtual DbSet<Tb_vuelo> Tb_vuelo { get; set; }
    
        public virtual ObjectResult<usp_ListaPasajeroPorPais_Result> usp_ListaPasajeroPorPais(string pais)
        {
            var paisParameter = pais != null ?
                new ObjectParameter("pais", pais) :
                new ObjectParameter("pais", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListaPasajeroPorPais_Result>("usp_ListaPasajeroPorPais", paisParameter);
        }
    
        public virtual ObjectResult<usp_ListarAsientosDisponiblesPorRucAerolinea_Result> usp_ListarAsientosDisponiblesPorRucAerolinea(string ruc)
        {
            var rucParameter = ruc != null ?
                new ObjectParameter("ruc", ruc) :
                new ObjectParameter("ruc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarAsientosDisponiblesPorRucAerolinea_Result>("usp_ListarAsientosDisponiblesPorRucAerolinea", rucParameter);
        }
    
        public virtual ObjectResult<usp_ListarPasajeros_Result> usp_ListarPasajeros()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarPasajeros_Result>("usp_ListarPasajeros");
        }
    
        public virtual ObjectResult<usp_ListarPasajerosPorFechaReserva_Result> usp_ListarPasajerosPorFechaReserva(string finicio, string ffin)
        {
            var finicioParameter = finicio != null ?
                new ObjectParameter("finicio", finicio) :
                new ObjectParameter("finicio", typeof(string));
    
            var ffinParameter = ffin != null ?
                new ObjectParameter("ffin", ffin) :
                new ObjectParameter("ffin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarPasajerosPorFechaReserva_Result>("usp_ListarPasajerosPorFechaReserva", finicioParameter, ffinParameter);
        }
    
        public virtual ObjectResult<usp_ListarVuelosDeAerolineasPorFechaRegistro_Result> usp_ListarVuelosDeAerolineasPorFechaRegistro(string finicio, string ffin)
        {
            var finicioParameter = finicio != null ?
                new ObjectParameter("finicio", finicio) :
                new ObjectParameter("finicio", typeof(string));
    
            var ffinParameter = ffin != null ?
                new ObjectParameter("ffin", ffin) :
                new ObjectParameter("ffin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarVuelosDeAerolineasPorFechaRegistro_Result>("usp_ListarVuelosDeAerolineasPorFechaRegistro", finicioParameter, ffinParameter);
        }
    }
}
