//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Reservas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_avion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_avion()
        {
            this.Tb_vuelo = new HashSet<Tb_vuelo>();
        }
    
        public int idAvion { get; set; }
        public int capacidad { get; set; }
        public string codigo { get; set; }
        public Nullable<System.DateTime> F_Registro { get; set; }
        public Nullable<System.DateTime> F_Modificacion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> idAerolinea { get; set; }
    
        public virtual Tb_aerolinea Tb_aerolinea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_vuelo> Tb_vuelo { get; set; }
    }
}
