//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Reservas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_departamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_departamento()
        {
            this.Tb_pais = new HashSet<Tb_pais>();
        }
    
        public int id_departamento { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> F_Registro { get; set; }
        public Nullable<System.DateTime> F_Modificacion { get; set; }
        public Nullable<int> estado { get; set; }
        public string foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_pais> Tb_pais { get; set; }
    }
}
