//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Reservas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_pago
    {
        public int idPago { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tipo_comprobante { get; set; }
        public string num_comprobante { get; set; }
        public string medio_pago { get; set; }
        public Nullable<System.DateTime> F_Registro { get; set; }
        public Nullable<System.DateTime> F_Modificacion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> idPasajero { get; set; }
        public Nullable<int> idReserva { get; set; }
        public string documento_pago { get; set; }
    
        public virtual Tb_pasajero Tb_pasajero { get; set; }
        public virtual Tb_reserva Tb_reserva { get; set; }
    }
}
