//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Reservas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_vuelo
    {
        public int idVuelo { get; set; }
        public Nullable<System.DateTime> F_Registro { get; set; }
        public Nullable<System.DateTime> F_Modificacion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> idAeropuerto { get; set; }
        public Nullable<int> idReserva { get; set; }
        public Nullable<int> idAsiento { get; set; }
        public Nullable<int> idAvion { get; set; }
        public Nullable<int> idDestino { get; set; }
    
        public virtual Tb_aeropuerto Tb_aeropuerto { get; set; }
        public virtual Tb_asiento Tb_asiento { get; set; }
        public virtual Tb_avion Tb_avion { get; set; }
        public virtual Tb_Destino Tb_Destino { get; set; }
        public virtual Tb_reserva Tb_reserva { get; set; }
    }
}
